# intake.py
#
# Handles transferring a structured pre-consultation intake summary
# (generated by the chat agent's `generate_doctor_intake_summary` tool)
# to the consulting doctor's dashboard on the PocketDoc Next.js app.
#
# This service has no database of its own — appointments/doctors live in
# PocketDoc's Postgres DB, owned by the Next.js app. So this endpoint acts
# as a relay: it validates the payload, then forwards it server-to-server
# to POCKETDOC_APP_URL + /api/intake/receive, authenticated with a shared
# secret so random callers can't write notes onto someone's appointment.
#
# Required environment variables:
#   POCKETDOC_APP_URL     e.g. https://pocketdoc-tan.vercel.app  (no trailing slash)
#   INTAKE_WEBHOOK_SECRET  a long random string, must match the same value
#                          set in the Next.js app's .env under the same name

import os
import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Literal, Optional

router = APIRouter()

POCKETDOC_APP_URL = os.getenv("POCKETDOC_APP_URL", "").rstrip("/")
INTAKE_WEBHOOK_SECRET = os.getenv("INTAKE_WEBHOOK_SECRET", "")


class IntakeSummary(BaseModel):
    chief_complaint: str
    symptom_duration: str
    severity_scale: Literal["LOW", "MODERATE", "HIGH", "EMERGENCY"]
    suspected_category: str
    summary_notes: str


class IntakeTransferRequest(BaseModel):
    intake_summary: IntakeSummary
    # If the patient has already booked an appointment, pass its id and
    # this endpoint will push the notes straight onto that appointment for
    # the doctor to see. If omitted, the summary is just validated and
    # echoed back — the frontend is responsible for attaching it once an
    # appointment is created (this is what the current PocketDoc frontend
    # does by default; see /api/appointments on the Next.js side).
    appointment_id: Optional[str] = None


@router.post("/transfer")
async def transfer_intake_to_doctor(payload: IntakeTransferRequest):
    if not payload.appointment_id:
        # No appointment yet — nothing to attach to. Return the validated
        # summary so the caller can hold onto it and send it along with
        # the booking request instead.
        return {
            "success": True,
            "forwarded": False,
            "reason": "No appointment_id provided; summary validated but not transferred.",
            "intake_summary": payload.intake_summary.model_dump(),
        }

    if not POCKETDOC_APP_URL or not INTAKE_WEBHOOK_SECRET:
        raise HTTPException(
            status_code=501,
            detail="POCKETDOC_APP_URL and INTAKE_WEBHOOK_SECRET must be set in this service's "
                   "environment to forward intake notes to the doctor dashboard.",
        )

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            res = await client.post(
                f"{POCKETDOC_APP_URL}/api/intake/receive",
                json={
                    "appointmentId": payload.appointment_id,
                    "intakeSummary": payload.intake_summary.model_dump(),
                },
                headers={"X-Intake-Secret": INTAKE_WEBHOOK_SECRET},
            )
    except httpx.RequestError as e:
        raise HTTPException(status_code=502, detail=f"Could not reach PocketDoc app: {str(e)}")

    if res.status_code == 404:
        raise HTTPException(status_code=404, detail="Appointment not found on PocketDoc app.")
    if res.status_code == 401:
        raise HTTPException(status_code=502, detail="Rejected by PocketDoc app: shared secret mismatch.")
    if res.status_code >= 400:
        raise HTTPException(status_code=502, detail=f"PocketDoc app responded with {res.status_code}: {res.text}")

    return {"success": True, "forwarded": True, "appointment_id": payload.appointment_id}
